[tool.black]
line-length = 79

[tool.ruff]
line-length = 79

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.mypy]
exclude = "doc/"

[[tool.mypy.overrides]]
# list all modules for which no type hints are available
module = [
    "ament_index_python.*",
    "cv2",
    "matplotlib.*",
    "pandas",
    "pinocchio",
    "plotext",
    "progressbar",
    "rclpy.*",
    "scipy.*",
    "setuptools",
    "std_msgs.*",
    "std_srvs.*",

    # our packages
    "robot_interfaces",
    "trifinger_cameras.*",
    "trifinger_simulation.*",
    "trifinger_object_tracking.*",

    # pybind11 packages
    "test_trifinger_build_workflows.pybullet_drivers",
    "test_trifinger_build_workflows.py_real_finger",
    "test_trifinger_build_workflows.py_trifinger",
    "test_trifinger_build_workflows.py_one_joint",
    "test_trifinger_build_workflows.py_two_joint",
    "test_trifinger_build_workflows.py_solo_eight",
]
ignore_missing_imports = true

