[intersphinx.mapping]
robot_interfaces = "https://open-dynamic-robot-initiative.github.io/robot_interfaces"

[mainpage]
title = "This is just a test!"
auto_general_docs = false

[html]
logo = "doc/images/trifinger_pictogram.png"
